version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      - GO111MODULE: on
      - GOLANG_VERSION: 1.13.6
      - K8S_VERSION: v1.15.0
#      - KIND_VERSION: v0.5.1
      - OPERATOR_SDK_VERSION: 0.14.0
    working_directory: /home/circleci/reaper-operator
    steps:
      - run:
          name: install golang
          command: |
            GOROOT=$(go env GOROOT)
            sudo rm -r $(go env GOROOT)
            sudo mkdir $GOROOT
            echo "Installing Go ${GOLANG_VERSION}"
            curl https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1
      - run:
          name: install operator-sdk
          command: |
            echo "Installing Operator SDK ${OPERATOR_SDK_VERSION}"
            curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v${OPERATOR_SDK_VERSION}/operator-sdk-v${OPERATOR_SDK_VERSION}-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/
      - run:
          name: Setup kubectl
          command: |
            wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config
      - checkout
      - restore_cache:
          key: build-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.go_workspace/pkg
      - run:
          name: run unit-tests
          command: |
            export GO111MODULE=on
            make unit-test
      - run:
          name: build e2e image
          command: |
            export GO111MODULE=on
            make build-e2e-image
      - save_cache:
          name: cache go modules
          key: build-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.go_workspace/pkg
      - deploy:
          name: Push image to docker hub
          command: |
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
            make push-image
      - run:
          name: install kind cluster
          command: |
            export GO111MODULE=on
            ./scripts/kind-smoketest.sh
            mv /home/circleci/kind /home/circleci/bin
      - save_cache:
          name: cache go modules
          key: build-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.go_workspace/pkg
      - run:
          name: run e2e tests
          command: |
            export GO111MODULE=on
            kind create cluster --name tlpstress
            export KUBECONFIG="$(kind get kubeconfig-path --name="reaper")"
            make e2e-test
          no_output_timeout: 15m
      - run:
          name: push tested image to docker hub
          command: |
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
            make push-image
